steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/chatapp-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/chatapp-backend:latest'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/chatapp-backend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/chatapp-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chatapp-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chatapp-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENV=production,PROJECT_ID=$PROJECT_ID,REGION=us-central1'
      - '--set-secrets'
      - 'POSTGRES_PASSWORD=db-password:latest,INFERENCE_API_KEY=openrouter-api-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/chatapp-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/chatapp-backend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'




