steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/chatapp/backend:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/chatapp/backend:latest'
      - '.'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/chatapp/backend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/chatapp/backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chatapp-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/chatapp/backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'ENV=production,PROJECT_ID=$PROJECT_ID,REGION=us-central1'
      - '--set-secrets'
      - 'POSTGRES_PASSWORD=postgres-password:latest,SAFETY_API_KEY=safety-api-key:latest,DATA_INTERPRETER_API_KEY=data-interpreter-api-key:latest'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/chatapp/backend:$SHORT_SHA'
  - 'us-central2-docker.pkg.dev/$PROJECT_ID/chatapp/backend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'




